version: "3.9"
services:
  postgres:
    image: postgres:17
    container_name: island-quiz-postgres
    restart: always
    env_file:
      - .env.${PROFILE:-development}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432
    volumes:
      - island-quiz-db:/var/lib/postgresql/data
    profiles:
      - dev
      - prod

  pgadmin:
    image: dpage/pgadmin4
    container_name: island-quiz-pgadmin
    restart: always
    env_file:
      - .env.development
    ports:
      - 5050:80
    depends_on:
      - postgres
    profiles:
      - dev
  
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: island-quiz-nextjs
    restart: always
    env_file:
      - .env.development
    ports:
      - 3000:3000 # For Next.js
      - 5555:5555 # For Prisma Studio
    depends_on:
      - postgres
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    profiles:
      - dev
    command: ["./entrypoint.sh"]

  app-prod:
    build:
      context: .
      dockerfile: Dockerfile
      target: release
    image: island-quiz-nextjs:latest
    container_name: island-quiz-nextjs
    restart: always
    env_file:
      - .env.production
    ports:
      - 3000:3000
    depends_on:
      - postgres:
          condition: service_healthy
    profiles:
      - prod

volumes:
  island-quiz-db: {}
