services:
  postgres:
    image: postgres:15
    container_name: island-quiz-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: island-quiz-db
    ports:
      - 5432:5432
    volumes:
      - island-quiz-db:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: island-quiz-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - 5050:80
    depends_on:
      - postgres
  
  app:
    build: .
    container_name: island-quiz-nextjs
    restart: always
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/island-quiz-db
    depends_on:
      - postgres

volumes:
  island-quiz-db:
