import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Toaster } from "react-hot-toast";
import "./globals.css";
import SessionWrapper from "@/components/SessionWrapper";

const inter = Inter({
	subsets: ["latin"],
	variable: "--font-primary"
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app"
};

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode;
}>) {

	return (
		<html lang="en">
			<body className={`${inter.variable} font-sans antialiased`}>
				<SessionWrapper>{children}</SessionWrapper>
				<Toaster position="top-right" />
			</body>
		</html>
	);
}
