name: CI for island-quiz-nextjs

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: island-quiz-db
        ports:
          - 5432:5432
        options:
          --health-cmd "pg_isready -U postgres -d island-quiz-db || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/island-quiz-db

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Wait for PostgreSQL to be ready
        run: |
          # Download wait-for-it.sh script
          wget https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh -O /usr/local/bin/wait-for-it.sh
          chmod +x /usr/local/bin/wait-for-it.sh

          echo "Waiting for PostgreSQL service at postgres:5432..."
          # Execute wait-for-it.sh, waiting for up to 60 seconds for PostgreSQL to be accessible.
          # The '--strict' flag ensures that the step fails if the service isn't available within the timeout.
          /usr/local/bin/wait-for-it.sh postgres:5432 --timeout=60 --strict
          echo "PostgreSQL is up and accessible!"

      - name: Generate Prisma Client
        run: npx prisma generate

      - name: Push Prisma schema
        run: npx prisma db push

      - name: Build Next.js app
        run: npm run build

      - name: Run tests
        run: npm test