name: CI for island-quiz-nextjs

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: island-quiz-db
        ports:
          - 5432:5432
        options: 
          --health-cmd pg_isready 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5
    env:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/island-quiz-db

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Wait for PostgreSQL port
        run: |
          for i in {1..10}; do
            nc -z postgres 5432 && echo "PostgreSQL port open" && exit 0
            echo "[$i/10] Waiting for PostgreSQL..."
            sleep 2
          done
          echo "PostgreSQL port not open after 10 tries"
          exit 1

      - name: Generate Prisma Client
        run: npx prisma generate

      - name: Push Prisma schema
        run: npx prisma db push

      - name: Build Next.js app
        run: npm run build

      - name: Run tests
        run: npm test