name: CI for island-quiz-nextjs

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    container: node:22-alpine

    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: island-quiz-db
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/island-quiz-db

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Install system deps for Prisma on Alpine
        run: |
          apk update && apk add --no-cache openssl

      - name: Push Prisma schema
        run: npx prisma db push

      - name: Generate Prisma client
        run: npx prisma generate

      - name: Build Next.js app
        run: npm run build

      - name: Run tests
        run: npm test